### ISSUE TITLE
Remove chat xss

### ISSUE THREAD

**Issue by michaljaz** [michaljaz/web-minecraft#12]
Remove vulnerability of xss in chat like "<script>alert('some js code')</script>".

**Comment by fox3000foxy** [comment]
I Can if you want

**Comment by michaljaz** [comment]
ok

**Comment by fox3000foxy** [comment]
you can close because i fix

**Comment by NexusNull** [comment]
fixed in https://github.com/michaljaz/web-minecraft/commit/bfb747d385889593eabfa5ab616dd84f75cea02b
