### ISSUE TITLE
Connect to custom server?

### ISSUE THREAD

**Issue by DakshG07** [michaljaz/web-minecraft#126]
I tried connecting to a cracked minecraft server(no Mojang acc needed) but it got stuck on loading terrain. The server was mc.herobrine.org at port 25565. Any help would be appreciated!

**Comment by michaljaz** [comment]
it supports currently max 1.16.5 servers

**Comment by michaljaz** [comment]
btw your server is working on webmc

**Comment by michaljaz** [comment]
interesting, I haven't dealt with such a problem yet
i will try to fix this

**Comment by Darkcatching73** [comment]
I'm smelling a blocked school network

**Comment by gwhizoftv** [comment]
We have a Paper server, and webmc just hangs when trying to connect.
