### ISSUE TITLE
socket.io convert to plain websockets

### ISSUE THREAD

**Issue by michaljaz** [michaljaz/web-minecraft#24]
use ws module in server and window.WebSocket in client

**Comment by NexusNull** [comment]
Why?

**Comment by KaffinPX** [comment]
websockets is fast.

**Comment by Project-Magenta** [comment]
fast

**Comment by NexusNull** [comment]
WebSocket: complicated

**Comment by RealPeha** [comment]
Hi @michaljaz!

Very interesting project 🙂

I think i can help you with ws implementation

**Comment by michaljaz** [comment]
cool

**Comment by RealPeha** [comment]
@michaljaz you have discord server or maybe some another group?

**Comment by michaljaz** [comment]
yeah in readme there is a badge https://discord.com/invite/h6DQzDx2G7
