### ISSUE TITLE
Tab list

### ISSUE THREAD

**Issue by fox3000foxy** [michaljaz/web-minecraft#28]

**Comment by KaffinPX** [comment]
uhmm

**Comment by fox3000foxy** [comment]
Why ?

**Comment by fox3000foxy** [comment]
Tab list show players list

**Comment by fox3000foxy** [comment]
Just recover with bot.players

**Comment by fox3000foxy** [comment]
Look mineflayer api

**Comment by michaljaz** [comment]
ah ok you mean this tab list

**Comment by fox3000foxy** [comment]
What other tab list ?

**Comment by fox3000foxy** [comment]
There is other tab list?

**Comment by fox3000foxy** [comment]
You think isaw for commands ? Its that ?

**Comment by fox3000foxy** [comment]
Commands dont work for thé moment, so not this tab list now !

**Comment by michaljaz** [comment]
yes, describe in more detail next time :)

**Comment by Picoseconds** [comment]
My fork has feat-tablist branch

**Comment by KaffinPX** [comment]
So make a pr for pulling?
