### ISSUE TITLE
Consider using prismarine-viewer and contributing to it

### ISSUE THREAD

**Issue by Karang** [michaljaz/web-minecraft#30]
prismarine-viewer is a library maintained by the prismarineJS community that provides functions to render a minecraft world.
It seems like you implemented some part of it, but you also implemented some features that are missing in prismarine-viewer and you are missing some other features. Both projects could be benefit if you decide to use prismarine-viewer for your rendering.

https://github.com/PrismarineJS/prismarine-viewer

https://prismarine.js.org/prismarine-viewer/

**Comment by KaffinPX** [comment]
Karang hi :)

**Comment by Heath123** [comment]
Closed with no explaination?

**Comment by michaljaz** [comment]
I will not use prismarine-viewer in web-minecraft. I have done too much work on it.
But I can help you growing prismarine-viewer.
