### ISSUE TITLE
Make inventory/heart/food bar high quality

### ISSUE THREAD

**Issue by KaffinPX** [michaljaz/web-minecraft#37]
Maybe using svg?

**Comment by fox3000foxy** [comment]
¯\_(ツ)_/¯

**Comment by michaljaz** [comment]
svg is bad option, because then it not depends on resourcepack

**Comment by michaljaz** [comment]
Only thing to do ic better cropping this images

**Comment by KaffinPX** [comment]
Youre right

**Comment by NexusNull** [comment]
I'm wondering, does minecraft offer the functionality to change the font?
Because if it does I need to manage that aswell, can't have discrepancies, right.

**Comment by Project-Magenta** [comment]
With resource packs it can, but we are not supporting resource packs

**Comment by Project-Magenta** [comment]
Using resource packs it can
