### ISSUE TITLE
Stuck on loading assets screen

### ISSUE THREAD

**Issue by EricAndrechek** [michaljaz/web-minecraft#40]
Running in Firefox on an iPad Air 4 iOS 14.4. Running vanilla mc server 1.16.5 offline mode.
Running web-minecraft latest commit in dev mode.

I suspect something funky is happening with WebKit html rendering over something like Chromium. In the web-minecraft logs I can see that my character is connecting, and in the minecraft server logs I see that the client connects successfully. 

Let me know what other information you would like from me, I am happy to help in debugging all that I can, I absolutely love this project idea!!

**Comment by EricAndrechek** [comment]
Ok, I opened up an old Mac computer to try running it in WebKit but it worked fine in the desktop version of Safari/WebKit. I then plugged in an iPad Air version 1 and connected to its console [like this](https://www.browserstack.com/guide/how-to-inspect-element-on-iphone). I think I found the underlying issue:

![image](https://user-images.githubusercontent.com/35144594/109593390-db916780-7ade-11eb-980c-7b23a300ed51.png)

It appears as though the function to lock in the mouse pointer for gameplay doesn't work on (this particular) mobile browser. I never even considered the fact that you may need to build in a touch screen interface. Regardless, in the case of my iPad Air 4, I was using it with a keyboard and mouse, but I suppose at this time Apple doesn't support those native javascript functions for this device. I wonder if there is some sort of workaround?

**Comment by Picoseconds** [comment]
There are no controls for touchscreen devices, and I doubt a bypass for pointer lock will be created before those controls are created. @NexusNull prove me wrong!

**Comment by michaljaz** [comment]
I think now it will not be worked on. I will focus on pc-like devices.

**Comment by fox3000foxy** [comment]
I think we should add controls for touchscreen devices @NexusNull  and @michaljaz 
I cna work on with KaffinPX

**Comment by fox3000foxy** [comment]
can

**Comment by KaffinPX** [comment]
But in this moment, we must focus on bugs/glitchs.
