### ISSUE TITLE
I cant "npm run build"

### ISSUE THREAD

**Issue by fox3000foxy** [michaljaz/web-minecraft#5]
cmd : sudo npm run build
result:
> web-minecraft@1.0.0 prebuild /home/lsannier/Desktop/web-minecraft
> node src/server/prebuild

Generated blocksDefinitions: /home/lsannier/Desktop/web-minecraft/src/server/../client/static/assets/blocks/blocksDef.json

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /home/lsannier/Desktop/web-minecraft/node_modules/canvas/lib/bindings.js
- /home/lsannier/Desktop/web-minecraft/node_modules/canvas/lib/canvas.js
- /home/lsannier/Desktop/web-minecraft/node_modules/canvas/index.js
- /home/lsannier/Desktop/web-minecraft/src/server/atlasCreator.js
- /home/lsannier/Desktop/web-minecraft/src/server/itemsAtlas.js
- /home/lsannier/Desktop/web-minecraft/src/server/prebuild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/lsannier/Desktop/web-minecraft/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lsannier/Desktop/web-minecraft/node_modules/canvas/lib/bindings.js',
    '/home/lsannier/Desktop/web-minecraft/node_modules/canvas/lib/canvas.js',
    '/home/lsannier/Desktop/web-minecraft/node_modules/canvas/index.js',
    '/home/lsannier/Desktop/web-minecraft/src/server/atlasCreator.js',
    '/home/lsannier/Desktop/web-minecraft/src/server/itemsAtlas.js',
    '/home/lsannier/Desktop/web-minecraft/src/server/prebuild.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-minecraft@1.0.0 prebuild: `node src/server/prebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-minecraft@1.0.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-30T08_46_25_105Z-debug.log

**Comment by fox3000foxy** [comment]
I cant use `webpack` CLI

**Comment by michaljaz** [comment]
Don't you forget "npm install"?

**Comment by michaljaz** [comment]
Btw you are running old version with javascript 
/home/lsannier/Desktop/web-minecraft/src/server/atlasCreator.js
/home/lsannier/Desktop/web-minecraft/src/server/itemsAtlas.js
/home/lsannier/Desktop/web-minecraft/src/server/prebuild.js
Try cloning latest version of repo with only coffeescript

**Comment by fox3000foxy** [comment]
no i have correctly "npm install"

**Comment by pofdzm** [comment]
Is that issue solved? I also have the same thing. Yes I also did the "npm install" too.
