### ISSUE TITLE
Use websocket to tcp proxy instead of node.js server

### ISSUE THREAD

**Issue by michaljaz** [michaljaz/web-minecraft#50]

**Comment by fox3000foxy** [comment]
Ok, but how ? Can u describe ?

**Comment by michaljaz** [comment]
javascript client in browser connects with websockets to proxy (that convert websocket to tcp) and then to minecraft server

**Comment by michaljaz** [comment]
that will be really fast

**Comment by fox3000foxy** [comment]
ok
so you want communication fast for fluid game
its that ?

**Comment by michaljaz** [comment]
yeah, prismarine-web-client done this :)

**Comment by fox3000foxy** [comment]
ok and how to do that ?

**Comment by fox3000foxy** [comment]
You ill wrote a function ?

**Comment by michaljaz** [comment]
Yeah I will fix this commit
