### ISSUE TITLE
webworkers number in dat gui panel

### ISSUE THREAD

**Issue by michaljaz** [michaljaz/web-minecraft#54]

**Comment by fox3000foxy** [comment]
What is it ?

**Comment by michaljaz** [comment]
more web workers that are generating chunk geometries. Terrain will generate faster.
You would change number of workers dynamically

**Comment by fox3000foxy** [comment]
Ok...

**Comment by fox3000foxy** [comment]
For faster renderer ?

**Comment by michaljaz** [comment]
no for generate chunk geometries faster.
Rendering faster will be if I add merging chunks

**Comment by fox3000foxy** [comment]
???

**Comment by fox3000foxy** [comment]
generate chunk model easier !?

**Comment by michaljaz** [comment]
To improve rendering speed I have to merge all chunk meshes into one mesh to get lower render calls

**Comment by fox3000foxy** [comment]
ok

**Comment by fox3000foxy** [comment]
can u go on discord plz ?

**Comment by fox3000foxy** [comment]
genered chunks are 3d model
