### ISSUE TITLE
Premium account support

### ISSUE THREAD

**Issue by michaljaz** [michaljaz/web-minecraft#9]
It is need to be added premium account support to play on 'online-mode=true' servers.
Premium password will be stored encrypted in cookies or localStorage.

**Comment by KaffinPX** [comment]
Dont store premium password, it will dangerious

**Comment by michaljaz** [comment]
ok, so every time if you want to play with premium, you'll must write it?

**Comment by michaljaz** [comment]
Or maybe storing only session id or something like that.
Something that let you play premium without logging in that expires after some time.

**Comment by KaffinPX** [comment]
I think its a good idea

**Comment by fox3000foxy** [comment]
Its cookie with expiration Time
If cookie already wroten, refresh exp date
Else,  register again
