### ISSUE TITLE
XSS vulnerability in tab list

### ISSUE THREAD

**Issue by antiafk** [michaljaz/web-minecraft#90]
https://github.com/michaljaz/web-minecraft/blob/73b57c617154f3f10d0d4ff28fcad53a9b338ba9/src/scripts/gui/TabList.js#L13

I would like to report an issue where you can use HTML tags in the tab list by defining your nickname with tags (like `<img src="a"/>` for example).

I would make a pull request, but I was having trouble installing the dependencies on Windows 10.

**Comment by michaljaz** [comment]
oh shit

**Comment by michaljaz** [comment]
fixed
